### PR TITLE
Gradle build file for the project

### PR DESCRIPTION
**Pull request by CloudNinja42**
Hi!

Just helped a friend create a Gradle build file for the project.  There's a few TODOs in the Gradle build file, but it was sufficient for his purposes.  Feel free to pull\discard based on whether you feel it adds some value to the project.

### CODE REVIEW

**Comment by CloudNinja42** [comment]
Let me know if you want me to tweak\improve anything and I can do that.  Its a build file, shouldn't take too long to make small tweaks...

**Comment by wangfei1975** [comment]
Hi Thanks for improve the project.

**Comment by wangfei1975** [comment]
Hi, I made further improvements on top of your changes. You can check it out from master branch if you are interested to take a look.
. use gson from mavenCentral
. pack dependencies jars into the runnable jar file depends on OS.
. pack resources into the runnable jar file

**Comment by CloudNinja42** [comment]
No thanks, I have enough work to do ;)  But awesome - seems you incorporated support for all the environments - excellent, thanks!!!  (I knew my implementation had some shortcomings, remember I just did this for a friend who isn't a Java developer but wanted to use your program)

I just sent you another pull request to fix a typo.  I did suddenly have a problem executing the Jar file, but then realized that strangely enough my 64-bit machine is running a 32-bit Jre.

Just out of interest, the error I got, very similar to this stackoverflow question:
http://stackoverflow.com/questions/11022600/cannot-load-64-bit-swt-libraries-on-32-bit-jvm-replacing-swt-file

**Pull request merged**
