### PR TITLE
Support selecting any part of a log line (and enable in place editing).

### PR DESCRIPTION
**Pull request by CoryXie**
Note that the in place table cell editing code should be attributed to http://www.java2s.com/Code/Java/SWT-JFace-Eclipse/editacellinaSWTtableinplacefancy.htm.

Signed-off-by: CoryXie <cory.xie@gmail.com>

### CODE REVIEW

**Comment by CoryXie** [comment]
Hi Fei,

This small feature is to allow the user to click any elements in the table items to select only part of interested text to copy, useful during debugging to copy some text to search the code base from things such as a OpenGrok server. Previously we were only able to select the whole line or several lines of log, which adds more effort to edit the text for search.

Sometime ago, I wanted to enable log editing and log annotation (adding accompany comments to logs) based on this feature, but that would take more efforts to implement...

I am using IntelliJ Idea and the tool made some auto formating to the code, hope you are OK with that. Maybe we could have some coding style defined, but using a common tool would also be an option?

Thanks,
Cory

**Comment by wangfei1975** [comment]
Thanks for the pull request. I will take a look soon.

**Comment by wangfei1975** [comment]
Hi Cory, 

I have tried your code, it is an interesting feature.  I agree that it is helpful to allow user copy part of the logs for search or other purpose.  However, it is sounds does not make a lot of sense to me to modify the logs. Add annotation is useful, but as you said that would need more effort to implement. 

At this time, can we disable the edit feature just allow user to select and copy logs partially. We can open a issue and discuss the better way to implement annotation. Another improvement we can make is that after  double click a word in the log , the word will be selected, then we can automatically fill it in search dialog if click search tool.

Also, can we customize the context menu when we active the TableEditor. The menu items of show unicode, insert unicode, show IME seems not consistent with the whole application. It is better to hide them.

Regarding code formatter, currently the whole project is using Eclipse build-in JAVA style and code formatter with a small change that use all spaces instead of TAB.

Thanks.

**Comment by CoryXie** [comment]
Hi Fei,

Thanks for trying it out. 

1) Regarding "disable the edit feature just allow user to select and copy logs partially", currently it only allows the user to double click the TableItem so the item is in edit mode, in this mode its easier for the user to select any text to copy. The user can actually edit the text in the item, but the edited text is not written back to the log file. In this regard, I think its OK to keep it this way, since modifying the log line (just for viewing it in another way) is a rare situation, and it might be useful sometimes (I myself had a time when a log text is printed wrong in the original code but wanted to make it look consistent with the code logic...). 

To be honest, without digging further, I don't know how exactly to implement it just allow the user select/copy partial text without putting the item into edit mode, the code was actually stolen from somewhere (as noted in the git log).

2) For log annotation and  copy a word automatically for pasting in search, yes, they look more complicated than they look. We can create issues to track. I had the annotation issue here https://github.com/CoryXie/superlog/issues/14.

3) For the context menu when edit mode is active, it seems to be platform dependent (SWT way of cross platform). On Ubuntu I don't see that kind of context menu, but it shows that context menu on Windows. Can we use an issue to track this? Software is a cumulative work.

Regards,
Cory

**Comment by wangfei1975** [comment]
Thanks for explanation. I'm OK for 1 and 2. Regarding context menu, I will create a issue to track this.

**Comment by wangfei1975** [comment]
Issue 12 been created to track this:
https://github.com/wangfei1975/superlog/issues/12

**Pull request merged**
